schema = Schema((

    StringField(
        name='Headline',
        widget=StringField._properties['widget'](
            label='Headline',
            label_msgid='Newspaper_label_Headline',
            i18n_domain='Newspaper',
        ),
    ),
    IntegerField(
	name='width',
	widget=IntegerField._properties['widget'](
	    label='width',
	    label_msgid='Newspaper_label_width',
	    i18n_domain='Newspaper',
	),
    ),
    IntegerField(
        name='Fontsize',
        widget=IntegerField._properties['widget'](
            label='Fontsize',
            label_msgid='Newspaper_label_Fontsize',
            i18n_domain='Newspaper',
        ),
    ), 
    StringField(
        name='headlineclass',
	default='headlineclass',
        widget=StringField._properties['widget'](
            label='Headline Class',
            label_msgid='Newspaper_label_headclass',
            i18n_domain='Newspaper',
        ),
    ),
    BooleanField(
	name='glueX',
        widget=BooleanField._properties['widget'](
	    label='glueX',
	    label_msgid='Newspaper_label_glueX',
	    i18n_domain='Newspaper',
	),
    ),
    BooleanField(
	name='glueY',
        widget=BooleanField._properties['widget'](
	    label='glueY',
	    label_msgid='Newspaper_label_glueY',
	    i18n_domain='Newspaper',
	),
    ),
    BooleanField(
	name='offsetX',
        widget=BooleanField._properties['widget'](
	    label='offsetX',
	    label_msgid='Newspaper_label_offsetX',
	    i18n_domain='Newspaper',
	),
    ),
    BooleanField(
	name='resetY',
        widget=BooleanField._properties['widget'](
	    label='resetY',
	    label_msgid='Newspaper_label_resetY',
	    i18n_domain='Newspaper',
	),
    ),
),
)
