    ReferenceField(
        name='article',
        widget=InAndOutWidget(
            label='Article',
            label_msgid='Newspaper_label_article',
            i18n_domain='Newspaper',
        ),
        allowed_types=('Wordage',),
        multiValued=1,
        relationship='containerLocation',
    ),
    IntegerField(
        name='startLine',
        widget=IntegerField._properties['widget'](
            label='StartLine',
            label_msgid='Newspaper_label_startLine',
            i18n_domain='Newspaper',
        ),
    ),
    IntegerField(
        name='endLine',
        widget=IntegerField._properties['widget'](
            label='EndLine',
            label_msgid='Newspaper_label_endLine',
            i18n_domain='Newspaper',
        ),
    ),
    BooleanField(
	name='useRemainder',
        widget=BooleanField._properties['widget'](
	    label='useRemainder',
	    label_msgid='Newspaper_label_useRemainder',
	    i18n_domain='Newspaper',
	),
    ),
    BooleanField(
	name='useContinuedOn',
        widget=BooleanField._properties['widget'](
	    label='useContinuedOn',
	    label_msgid='Newspaper_label_useContinuedOn',
	    i18n_domain='Newspaper',
	),
    ),
    StringField(
        name='continuedOn',
	default='Continued on Page Four',
        widget=StringField._properties['widget'](
            label='Continued On',
            label_msgid='Newspaper_label_continuedon',
            i18n_domain='Newspaper',
        ),
    ),
    BooleanField(
	name='useContinuedFrom',
        widget=BooleanField._properties['widget'](
	    label='useContinuedFrom',
	    label_msgid='Newspaper_label_useContinuedFrom',
	    i18n_domain='Newspaper',
	),
    ),
    StringField(
        name='continuedFrom',
	default='Continued From Page One',
        widget=StringField._properties['widget'](
            label='Continued From',
            label_msgid='Newspaper_label_continuedfrom',
            i18n_domain='Newspaper',
        ),
    ),
    IntegerField(
	name='charsPerLine',
	widget=IntegerField._properties['widget'](
            label='Characters per Line',
	    label_msgid='Newspaper_label_charsPerLine',
	    i18n_domain='Newspaper',
	),
    ),
    IntegerField(
	name='offsetXWidth',
	default=0,
	widget=IntegerField._properties['widget'](
            label='X Column Offset',
	    label_msgid='Newspaper_label_offsetXWidth',
	    i18n_domain='Newspaper',
	),
    ),
    IntegerField(
	name='offsetYHeight',
	default=0,
	widget=IntegerField._properties['widget'](
            label='Y Column Offset',
	    label_msgid='Newspaper_label_offsetXWidth',
	    i18n_domain='Newspaper',
	),
    ),
    StringField(
        name='textclass',
	default='textclass',
        widget=StringField._properties['widget'](
            label='Text class',
            label_msgid='Newspaper_label_textclass',
            i18n_domain='Newspaper',
        ),
    ),
    BooleanField(
	name='glueX',
        widget=BooleanField._properties['widget'](
	    label='glueX',
	    label_msgid='Newspaper_label_glueX',
	    i18n_domain='Newspaper',
	),
    ),
    BooleanField(
	name='glueY',
        widget=BooleanField._properties['widget'](
	    label='glueY',
	    label_msgid='Newspaper_label_glueY',
	    i18n_domain='Newspaper',
	),
    ),
    BooleanField(
	name='offsetX',
        widget=BooleanField._properties['widget'](
	    label='offsetX',
	    label_msgid='Newspaper_label_offsetX',
	    i18n_domain='Newspaper',
	),
    ),
    BooleanField(
	name='resetY',
        widget=BooleanField._properties['widget'](
	    label='resetY',
	    label_msgid='Newspaper_label_resetY',
	    i18n_domain='Newspaper',
	),
    ),
    BooleanField(
	name='addLineHeight',
        widget=BooleanField._properties['widget'](
	    label='addLineHeight',
	    label_msgid='Newspaper_label_addLineHeight',
	    i18n_domain='Newspaper',
	),
    ),
),
)
